# Generated by Django 5.0.6 on 2026-06-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leiloes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovelcaixa',
            name='area_terreno',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='imovelcaixa',
            name='area_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='imovelcaixa',
            name='bairro',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imovelcaixa',
            name='data_geracao_lista',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imovelcaixa',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='imovelcaixa',
            name='detalhe_atualizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imovelcaixa',
            name='detalhes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='imovelcaixa',
            name='link_caixa',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='imovelcaixa',
            name='modalidade_venda',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='imovelcaixa',
            name='situacao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='imovelcaixa',
            name='data_leilao',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='imovelcaixa',
            name='ocupado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imovelcaixa',
            name='tipo',
            field=models.CharField(choices=[('apto', 'Apartamento'), ('casa', 'Casa'), ('sala', 'Sala Comercial'), ('lote', 'Lote'), ('galpao', 'Galpão'), ('outro', 'Outro')], db_index=True, max_length=20),
        ),
    ]
