# Generated by Django 5.0.6 on 2026-06-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leiloes', '0002_imovelcaixa_area_terreno_imovelcaixa_area_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovelcaixa',
            name='area_terreno',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='imovelcaixa',
            name='area_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='imovelcaixa',
            name='area_util',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
