# Generated by Codex on 2026-06-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leiloes', '0003_alter_imovelcaixa_area_terreno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovelcaixa',
            name='ativo_caixa',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='imovelcaixa',
            name='ultima_sincronizacao_caixa',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='imovelcaixa',
            name='removido_da_caixa_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
