[build]
builder = "NIXPACKS"

[deploy]
preDeployCommand = ["python manage.py migrate --settings=config.settings.production"]
startCommand = "python manage.py collectstatic --noinput --settings=config.settings.production && PLAYWRIGHT_BROWSERS_PATH=/app/.cache/ms-playwright gunicorn config.wsgi --workers 2 --threads 4 --timeout 120 --access-logfile - --error-logfile - --capture-output"
healthcheckPath = "/healthz/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
