# Generated by Django 5.0.6 on 2026-06-02 17:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(choices=[('AC', 'AC — Acre'), ('AL', 'AL — Alagoas'), ('AM', 'AM — Amazonas'), ('AP', 'AP — Amapá'), ('BA', 'BA — Bahia'), ('CE', 'CE — Ceará'), ('DF', 'DF — Distrito Federal'), ('ES', 'ES — Espírito Santo'), ('GO', 'GO — Goiás'), ('MA', 'MA — Maranhão'), ('MG', 'MG — Minas Gerais'), ('MS', 'MS — Mato Grosso do Sul'), ('MT', 'MT — Mato Grosso'), ('PA', 'PA — Pará'), ('PB', 'PB — Paraíba'), ('PE', 'PE — Pernambuco'), ('PI', 'PI — Piauí'), ('PR', 'PR — Paraná'), ('RJ', 'RJ — Rio de Janeiro'), ('RN', 'RN — Rio Grande do Norte'), ('RO', 'RO — Rondônia'), ('RR', 'RR — Roraima'), ('RS', 'RS — Rio Grande do Sul'), ('SC', 'SC — Santa Catarina'), ('SE', 'SE — Sergipe'), ('SP', 'SP — São Paulo'), ('TO', 'TO — Tocantins')], default='BA', max_length=2, verbose_name='Estado (UF)')),
                ('etapa', models.CharField(choices=[('oportunidade', '🎯 Oportunidade'), ('arrematado', '🔨 Arrematado'), ('documentacao', '📋 Documentação'), ('reforma', '🏗️ Reforma'), ('a_venda', '📢 À Venda'), ('concluido', '✅ Concluído')], default='oportunidade', max_length=20, verbose_name='Etapa')),
                ('tipo_leilao', models.CharField(choices=[('Extrajudicial', 'Extrajudicial'), ('Judicial', 'Judicial')], default='Extrajudicial', max_length=20, verbose_name='Tipo de leilão')),
                ('obs', models.TextField(blank=True, verbose_name='Observações')),
                ('avaliacao', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor de avaliação (R$)')),
                ('lance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Lance (R$)')),
                ('tipo_pgto', models.CharField(choices=[('À Vista', 'À Vista'), ('Financiamento SAC', 'Financiamento SAC')], default='À Vista', max_length=20, verbose_name='Pagamento')),
                ('entrada', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Entrada (%)')),
                ('prazo_fin', models.PositiveIntegerField(default=0, verbose_name='Prazo financiamento (meses)')),
                ('cet_aa', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='CET (% a.a.)')),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Preço de venda (R$)')),
                ('taxa_acrescimo', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa acréscimo venda (%)')),
                ('desconto_venda', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Desconto venda (%)')),
                ('rec_aluguel_am', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Receita aluguel/mês (R$)')),
                ('pct_corretor', models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='Corretor (%)')),
                ('pct_itbi_base', models.CharField(choices=[('Arrematação', 'Arrematação'), ('Avaliação Fiscal', 'Avaliação Fiscal')], default='Arrematação', max_length=20, verbose_name='Base ITBI')),
                ('aliq_itbi', models.DecimalField(decimal_places=2, default=2, max_digits=5, verbose_name='Alíquota ITBI (%)')),
                ('aliq_itbi_fin', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alíq. fração financiada (%)')),
                ('modo_cartorio', models.CharField(choices=[('Automático', 'Automático'), ('Manual', 'Manual')], default='Automático', max_length=10, verbose_name='Modo cartório')),
                ('av_fiscal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Avaliação fiscal (R$)')),
                ('escritura_manual', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Escritura manual (R$)')),
                ('registro_manual', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Registro manual (R$)')),
                ('pct_leiloeiro', models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='Comissão leiloeiro (%)')),
                ('reformas', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Reformas (R$)')),
                ('custo_desocup', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Custo desocupação (R$)')),
                ('debitos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Débitos (R$)')),
                ('despesas_div', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Despesas diversas (R$)')),
                ('laudemio_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Laudêmio (%)')),
                ('meses_titulo', models.PositiveIntegerField(default=0, verbose_name='Meses até título')),
                ('iptu_am', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IPTU mensal (R$)')),
                ('cond_am', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Condomínio mensal (R$)')),
                ('custo_oport_aa', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Rendimento alternativo (% a.a.)')),
                ('tipo_pessoa', models.CharField(choices=[('Pessoa Física', 'Pessoa Física'), ('Pessoa Jurídica', 'Pessoa Jurídica')], default='Pessoa Física', max_length=20, verbose_name='Tributação IR')),
                ('lucro_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Lucro mínimo desejado (R$)')),
                ('incremento_lance', models.DecimalField(decimal_places=2, default=5000, max_digits=12, verbose_name='Incremento de lance (R$)')),
                ('giro_padrao', models.IntegerField(choices=[(1, '1 meses'), (3, '3 meses'), (4, '4 meses'), (6, '6 meses'), (7, '7 meses'), (9, '9 meses'), (10, '10 meses'), (12, '12 meses')], default=12, verbose_name='Giro padrão (meses)')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imoveis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
