# Generated by Django 5.0.6 on 2026-06-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='data_leilao',
            field=models.DateField(blank=True, null=True, verbose_name='Data do leilão'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imoveis/fotos/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='link_leilao',
            field=models.URLField(blank=True, verbose_name='Link do leilão'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='tipo_imovel',
            field=models.CharField(choices=[('apartamento', 'Apartamento'), ('casa', 'Casa'), ('terreno', 'Terreno'), ('comercial', 'Comercial'), ('rural', 'Rural'), ('outros', 'Outros')], default='apartamento', max_length=20, verbose_name='Tipo de imóvel'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='etapa',
            field=models.CharField(choices=[('estoque', 'Estoque'), ('triagem_financeira', 'Triagem Financeira'), ('triagem_juridica', 'Triagem Jurídica'), ('debate_final', 'Debate Final e Decisão'), ('participacao_leilao', 'Participação Leilão'), ('registro_desocupacao', 'Registro e Desocupação'), ('reforma', 'Reforma'), ('procedimento_venda', 'Procedimento de Venda'), ('vendido_ir', 'Vendido (Aguardando IR)'), ('operacao_finalizada', 'Operação Finalizada'), ('arquivado', 'Arquivado')], default='estoque', max_length=30, verbose_name='Etapa'),
        ),
    ]
