# Generated by Django 5.0.6 on 2026-06-04 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_imovel_data_leilao_imovel_foto_imovel_link_leilao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='caixa_imovel_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='ID do imóvel Caixa'),
        ),
        migrations.AddConstraint(
            model_name='imovel',
            constraint=models.UniqueConstraint(condition=models.Q(('caixa_imovel_id', ''), _negated=True), fields=('user', 'caixa_imovel_id'), name='unique_imovel_caixa_por_usuario'),
        ),
    ]
