# Generated by Django 5.0.6 on 2026-06-05 14:07

import apps.imoveis.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_imovel_caixa_imovel_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='titulo_personalizado',
            field=models.CharField(blank=True, max_length=160, verbose_name='Título personalizado'),
        ),
        migrations.CreateModel(
            name='ImovelArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=apps.imoveis.models.imovel_arquivo_upload_to, verbose_name='Arquivo')),
                ('nome', models.CharField(blank=True, max_length=180, verbose_name='Nome')),
                ('categoria', models.CharField(choices=[('apoio', 'Apoio'), ('matricula', 'Matrícula'), ('edital', 'Edital'), ('foto', 'Foto'), ('financeiro', 'Financeiro'), ('outro', 'Outro')], default='apoio', max_length=20, verbose_name='Categoria')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivos_imoveis', to=settings.AUTH_USER_MODEL)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='imoveis.imovel')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ImovelComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentário')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='imoveis.imovel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_imoveis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ImovelChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('estoque', 'Estoque'), ('triagem_financeira', 'Triagem Financeira'), ('triagem_juridica', 'Triagem Jurídica'), ('debate_final', 'Debate Final e Decisão'), ('participacao_leilao', 'Participação Leilão'), ('registro_desocupacao', 'Registro e Desocupação'), ('reforma', 'Reforma'), ('procedimento_venda', 'Procedimento de Venda'), ('vendido_ir', 'Vendido (Aguardando IR)'), ('operacao_finalizada', 'Operação Finalizada'), ('arquivado', 'Arquivado')], db_index=True, max_length=30, verbose_name='Etapa')),
                ('texto', models.CharField(max_length=320, verbose_name='Item')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluído')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_items_criados', to=settings.AUTH_USER_MODEL)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='imoveis.imovel')),
            ],
            options={
                'ordering': ['etapa', 'ordem', 'id'],
                'indexes': [models.Index(fields=['imovel', 'etapa'], name='imoveis_imo_imovel__4c4562_idx')],
            },
        ),
    ]
