# Generated by Django 5.0.6 on 2026-06-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0004_imovel_titulo_personalizado_imovelarquivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='analise_juridica_ia',
            field=models.JSONField(blank=True, null=True, verbose_name='Análise jurídica IA'),
        ),
    ]
