# Generated by Django 5.0.6 on 2026-06-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0005_add_analise_juridica_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='arquivado_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Arquivado em'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='motivo_arquivamento',
            field=models.CharField(blank=True, choices=[('leilao_encerrado', 'Leilão encerrado'), ('sem_interesse', 'Sem interesse'), ('duplicado', 'Duplicado'), ('aguardar', 'Aguardar depois'), ('outro', 'Outro')], max_length=30, verbose_name='Motivo do arquivamento'),
        ),
    ]
