# Generated by Django 5.0.6 on 2026-06-23 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0006_imovel_arquivado_em_imovel_motivo_arquivamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImovelCompartilhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissao', models.CharField(choices=[('leitura', 'Somente leitura'), ('edicao', 'Pode editar')], max_length=20, verbose_name='Permissão')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compartilhamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compartilhamentos', to='imoveis.imovel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imoveis_compartilhados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compartilhamento de imóvel',
                'verbose_name_plural': 'Compartilhamentos de imóveis',
                'ordering': ['user__first_name', 'user__username'],
                'indexes': [models.Index(fields=['user', 'ativo'], name='imoveis_imo_user_id_b15e5b_idx'), models.Index(fields=['imovel', 'ativo'], name='imoveis_imo_imovel__6f8011_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='imovelcompartilhamento',
            constraint=models.UniqueConstraint(fields=('imovel', 'user'), name='unique_compartilhamento_imovel_usuario'),
        ),
    ]
