# Generated by Django 5.0.6 on 2026-06-23 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0007_imovelcompartilhamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compartilhamento', 'Compartilhamento')], default='compartilhamento', max_length=30, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=160, verbose_name='Título')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='URL interna')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lida_em', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('imovel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='imoveis.imovel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['user', 'lida_em'], name='imoveis_not_user_id_5f78da_idx'), models.Index(fields=['user', 'criado_em'], name='imoveis_not_user_id_a386e4_idx')],
            },
        ),
    ]
