# Generated by Django 5.0.6 on 2026-06-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0009_imovel_documentos_texto_chatimovel_chatmensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovelarquivo',
            name='categoria',
            field=models.CharField(choices=[('apoio', 'Apoio'), ('matricula', 'Matrícula'), ('edital', 'Edital'), ('processo', 'Processo judicial'), ('certidao', 'Certidão'), ('foto', 'Foto'), ('financeiro', 'Financeiro'), ('outro', 'Outro')], default='apoio', max_length=20, verbose_name='Categoria'),
        ),
    ]
