# Generated by Django 5.0.6 on 2026-06-28 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartorioTabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, max_length=2, verbose_name='UF')),
                ('ano', models.PositiveSmallIntegerField(db_index=True, verbose_name='Ano')),
                ('tipo', models.CharField(choices=[('escritura', 'Escritura'), ('registro', 'Registro')], db_index=True, max_length=20, verbose_name='Tipo')),
                ('vigente_inicio', models.DateField(db_index=True, verbose_name='Início da vigência')),
                ('vigente_fim', models.DateField(blank=True, db_index=True, null=True, verbose_name='Fim da vigência')),
                ('fonte_nome', models.CharField(max_length=180, verbose_name='Fonte')),
                ('fonte_url', models.URLField(blank=True, max_length=600, verbose_name='URL da fonte oficial')),
                ('fundamento', models.CharField(blank=True, max_length=220, verbose_name='Fundamento/ato normativo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('pendente_validacao', 'Pendente de validação'), ('validada', 'Validada'), ('substituida', 'Substituída')], db_index=True, default='pendente_validacao', max_length=30, verbose_name='Status')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativa')),
                ('conferido_em', models.DateTimeField(blank=True, null=True, verbose_name='Conferido em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conferido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartorio_tabelas_conferidas', to=settings.AUTH_USER_MODEL, verbose_name='Conferido por')),
            ],
            options={
                'verbose_name': 'Tabela cartorária',
                'verbose_name_plural': 'Tabelas cartorárias',
                'ordering': ['uf', '-vigente_inicio', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='CartorioFaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(verbose_name='Ordem')),
                ('limite_superior', models.DecimalField(blank=True, decimal_places=2, help_text='Deixe vazio para representar a última faixa sem limite.', max_digits=14, null=True, verbose_name='Limite superior')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor do emolumento')),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas', to='calculadora.cartoriotabela')),
            ],
            options={
                'verbose_name': 'Faixa cartorária',
                'verbose_name_plural': 'Faixas cartorárias',
                'ordering': ['tabela', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='CartorioRegraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, max_length=2, verbose_name='UF')),
                ('ano', models.PositiveSmallIntegerField(db_index=True, verbose_name='Ano')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('percentual', models.DecimalField(decimal_places=4, help_text='Ex.: 0,1000 para 0,1%.', max_digits=7, verbose_name='Percentual (%)')),
                ('vigente_inicio', models.DateField(db_index=True, verbose_name='Início da vigência')),
                ('vigente_fim', models.DateField(blank=True, db_index=True, null=True, verbose_name='Fim da vigência')),
                ('fonte_nome', models.CharField(max_length=180, verbose_name='Fonte')),
                ('fonte_url', models.URLField(blank=True, max_length=600, verbose_name='URL da fonte oficial')),
                ('fundamento', models.CharField(blank=True, max_length=220, verbose_name='Fundamento/ato normativo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('pendente_validacao', 'Pendente de validação'), ('validada', 'Validada'), ('substituida', 'Substituída')], db_index=True, default='pendente_validacao', max_length=30, verbose_name='Status')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativa')),
                ('conferido_em', models.DateTimeField(blank=True, null=True, verbose_name='Conferido em')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conferido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartorio_extras_conferidos', to=settings.AUTH_USER_MODEL, verbose_name='Conferido por')),
            ],
            options={
                'verbose_name': 'Regra extra cartorária',
                'verbose_name_plural': 'Regras extras cartorárias',
                'ordering': ['uf', '-vigente_inicio', 'nome'],
                'indexes': [models.Index(fields=['uf', 'ativo', 'vigente_inicio'], name='calculadora_uf_baa8b8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='cartorioregraextra',
            constraint=models.UniqueConstraint(fields=('uf', 'ano', 'nome', 'vigente_inicio'), name='uniq_cartorio_extra_uf_ano_nome_vigencia'),
        ),
        migrations.AddIndex(
            model_name='cartoriotabela',
            index=models.Index(fields=['uf', 'tipo', 'ativo', 'vigente_inicio'], name='calculadora_uf_bef3e3_idx'),
        ),
        migrations.AddIndex(
            model_name='cartoriotabela',
            index=models.Index(fields=['uf', 'ano', 'tipo'], name='calculadora_uf_b03c64_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartoriotabela',
            constraint=models.UniqueConstraint(fields=('uf', 'ano', 'tipo', 'vigente_inicio'), name='uniq_cartorio_tabela_uf_ano_tipo_vigencia'),
        ),
        migrations.AddIndex(
            model_name='cartoriofaixa',
            index=models.Index(fields=['tabela', 'ordem'], name='calculadora_tabela__cff6e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartoriofaixa',
            constraint=models.UniqueConstraint(fields=('tabela', 'ordem'), name='uniq_cartorio_faixa_ordem'),
        ),
    ]
