# Generated by Django 5.0.6 on 2026-06-28 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartorioFonteMonitorada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, max_length=2, verbose_name='UF')),
                ('nome', models.CharField(max_length=180, verbose_name='Nome')),
                ('url', models.URLField(max_length=600, unique=True, verbose_name='URL oficial monitorada')),
                ('ativa', models.BooleanField(db_index=True, default=True, verbose_name='Ativa')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ultimo_hash', models.CharField(blank=True, max_length=64, verbose_name='Último hash')),
                ('ultimo_status_http', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Último status HTTP')),
                ('ultimo_content_type', models.CharField(blank=True, max_length=180, verbose_name='Último content-type')),
                ('ultimo_tamanho_bytes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Último tamanho em bytes')),
                ('ultimo_etag', models.CharField(blank=True, max_length=255, verbose_name='Último ETag')),
                ('ultimo_last_modified', models.CharField(blank=True, max_length=255, verbose_name='Último Last-Modified')),
                ('verificada_em', models.DateTimeField(blank=True, null=True, verbose_name='Verificada em')),
                ('alterada_em', models.DateTimeField(blank=True, null=True, verbose_name='Alterada em')),
                ('ultimo_erro', models.TextField(blank=True, verbose_name='Último erro')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fonte cartorária monitorada',
                'verbose_name_plural': 'Fontes cartorárias monitoradas',
                'ordering': ['uf', 'nome'],
                'indexes': [models.Index(fields=['uf', 'ativa'], name='calculadora_uf_644f4d_idx'), models.Index(fields=['ativa', 'verificada_em'], name='calculadora_ativa_61ff17_idx')],
            },
        ),
        migrations.CreateModel(
            name='CartorioFonteEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mudanca_detectada', 'Mudança detectada'), ('erro', 'Erro de monitoramento')], db_index=True, max_length=30, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('revisado', 'Revisado'), ('ignorado', 'Ignorado')], db_index=True, default='pendente', max_length=20, verbose_name='Status')),
                ('hash_anterior', models.CharField(blank=True, max_length=64, verbose_name='Hash anterior')),
                ('hash_novo', models.CharField(blank=True, max_length=64, verbose_name='Hash novo')),
                ('status_http', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Status HTTP')),
                ('content_type', models.CharField(blank=True, max_length=180, verbose_name='Content-type')),
                ('tamanho_bytes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamanho em bytes')),
                ('mensagem', models.CharField(max_length=260, verbose_name='Mensagem')),
                ('detalhe', models.TextField(blank=True, verbose_name='Detalhe')),
                ('detectado_em', models.DateTimeField(auto_now_add=True, verbose_name='Detectado em')),
                ('resolvido_em', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartorio_fonte_eventos_resolvidos', to=settings.AUTH_USER_MODEL, verbose_name='Resolvido por')),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='calculadora.cartoriofontemonitorada', verbose_name='Fonte')),
            ],
            options={
                'verbose_name': 'Evento de fonte cartorária',
                'verbose_name_plural': 'Eventos de fonte cartorária',
                'ordering': ['-detectado_em'],
                'indexes': [models.Index(fields=['status', 'tipo', 'detectado_em'], name='calculadora_status_f733a5_idx'), models.Index(fields=['fonte', 'status'], name='calculadora_fonte_i_dfc70d_idx')],
            },
        ),
    ]
