# Generated by Django 5.0.6 on 2026-06-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0002_cartoriofontemonitorada_cartoriofonteevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoriofonteevento',
            name='aplicacao_automatica',
            field=models.BooleanField(default=False, verbose_name='Aplicação automática'),
        ),
        migrations.AddField(
            model_name='cartoriofonteevento',
            name='extras_afetados',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Regras extras afetadas'),
        ),
        migrations.AddField(
            model_name='cartoriofonteevento',
            name='tabelas_afetadas',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Tabelas afetadas'),
        ),
    ]
